
language: node_js

cache:
    directories:
        - node_modules

branches:
    only:
        - master

env:
    global:
        - NODE_ENV=production

deploy:
    provider: firebase
    token:
        secure: DP9Q+fNP2UnJnOfMXNbaEtyPnwrdr7Q5ymHyQAjL9/rIbH1z9WVGzVE8YQyjjdG3eZA1nLat5L9i20fpgrDe6pAkf5FI0xtS6P7hNHSs0CL9zr9+TTuswW+YpRbD1DGlB83lmkETKKYPTaC2Sc4cCLLcUTl8/UiRokUQf33ZhuquSnqr4dQ2z0w55mNMF8lmU1AUocgGhmOXjtk1I60BLN0/drAo/nxbMwrT5rXdjp+I1/IoEOENtzcqfzjFDya5mP2ao5m9WnPsakM1v1gUyAecBdkRDboyJBLsyWEbJ5mPxagJSLER/8uqbdrk9dCFX7s1Y1YYdyEE8xOx5xoeD5fbd+F+OctGu0YHF5/4hNGu+U7oz1pF2t8Hp9VVwXqlTmz6Px+Dz1dZxEXj5WX7t42nP8Xh5pT8NLh92c0m5AnXDKo2yCAm6R+DnkkcWwE5BXCZDB4HNfaVB4WVemLf+g7IMkJN5ew98FJKKIpxY0uCiD9xjWZhFWlL1nW6TqXevHmARSWIERhbylfrws5mlSuGMT3LmAHdy8wKODo7lL9YPRuNrYnqMibdKahfjmvhNHiYjTZCFiA41abEC5ycDh75MhFu/7EX0nYzcS7hN7xzatWpQjBXx/OCjIpfMdsoV6rsN7ZQ9gmJcR9YdtsmLoxlWOQoahvQlI+j1H7Fhwg=
    skip_cleanup: true
    on:
        branch:
            - master
