
language: node_js

cache:
    directories:
        - node_modules

env:
    global:
        - NODE_ENV=production

deploy:
    provider: firebase
    token:
        secure: WHHlHBJGpFMObwM1qcSrwV5/Ipr1kdaSjDc0flFGNIGPPQH0i58z5GxqvAVbCXY4Wnc7Z3pZxHcIqKMt6jDat1SAJ+LfWRqxXiXYpe/B9WD4V2DeYQRjsE9ffRH0yyFnOh71RvTpDWOlEkpP8PtTqo3r1rUo7vBaraJ6V/itz74nzWIU+UTEundmAQgQ8BFRGtYnFaU0MJDNkiYPSMgNYD4viRdB9CmXAvQ2dHAkxwwtDmMVzvNgipaWdsvrXgirKDQWs8c9LKGED4mgqp/1SUapxLjRCi3BzfgmB9vUzYo9r0FQfeuxYlt5zMnOlMLs/M216l3cMFs/PnCOFAZT0B6J0029HKC2ej1iHd9Vz5dspppITznbYqn4VxdbsLLD4F0uvbt+6LYuUSIPwOrboDn/WSv6D0Wdz7qqgFJuZAtMHs3cFTr0eUYwi7QERGiTdQZIDhbJmubr0w40P4t+vkIJ2YCkRpkQq2hNeRZD7z6R5D2Zf+RscLw6O86t56TML70PwvyXnWgVtIJ+DaInF05CIQljbY70AD29n0N8a3ExniQVWUiPj4HvqGODWVnQgIPdVO7M5HqDW1/BxEu6krDNO+45OofOGeZLfR2hEj2nMSC6+bTMXgokuyE6nVgGjv3X23haFoHpF1U8Giw1KMBlg104UsreXiUnU7hEng4=
    skip_cleanup: true
    on:
        branch:
            - master
